# Generated by Django 6.0 on 2025-12-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_token',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
